# Generated by Django 4.1 on 2022-10-03 04:03

import ckeditor.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('subtitulo', models.CharField(max_length=1000)),
                ('categoria', models.CharField(choices=[('Europa', 'europa'), ('Asia', 'asia'), ('Sudamerica', 'sudamerica'), ('Centro América', 'centro america'), ('Norte América', 'norte america'), ('Oceania', 'oceania'), ('Africa', 'africa')], max_length=100)),
                ('pais', models.CharField(max_length=1000)),
                ('cuerpo', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='experiencias')),
                ('fecha', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='avatares')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
